services:
  mydatalab:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/inzhenerka/mydatalab:latest
    container_name: mydatalab
    ports:
      - "8888:8888" # Jupyter
      - "4040:4040" # Spark UI
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
      - "8181:8181" # Lakekeeper UI & REST
      - "1111:1111" # Landing page
      - "9010:9010" # Supervisor UI
      - "6432:5432" # PostgreSQL
    volumes:
      - ./notebooks/iceberg:/home/jovyan/iceberg
      - ./jupyter-work:/home/jovyan/work
      - ./minio-data:/data/minio
      - ./postgres-data:/home/jovyan/postgres-data:Z
    restart: no
