gravitino.server.shutdown.timeout = 3000
gravitino.server.webserver.host = ${GRAVITINO_WEB_HOST}
gravitino.server.webserver.httpPort = ${GRAVITINO_WEB_PORT}
gravitino.server.webserver.minThreads = 24
gravitino.server.webserver.maxThreads = 200
gravitino.server.webserver.stopTimeout = 30000
gravitino.server.webserver.idleTimeout = 30000
gravitino.server.webserver.threadPoolWorkQueueSize = 100
gravitino.server.webserver.requestHeaderSize = 131072
gravitino.server.webserver.responseHeaderSize = 131072

gravitino.entity.store = relational
gravitino.entity.store.relational = JDBCBackend
gravitino.entity.store.relational.jdbcUrl = ${GRAVITINO_STORE_JDBC}
gravitino.entity.store.relational.jdbcDriver = ${GRAVITINO_STORE_DRIVER}
gravitino.entity.store.relational.jdbcUser = ${GRAVITINO_STORE_USER}
gravitino.entity.store.relational.jdbcPassword = ${GRAVITINO_STORE_PASSWORD}
gravitino.entity.store.relational.jdbcInitialize = true

gravitino.authorization.enable = false
gravitino.authorization.serviceAdmins = anonymous

gravitino.auxService.names = iceberg-rest
gravitino.iceberg-rest.classpath = iceberg-rest-server/libs, iceberg-rest-server/conf
gravitino.iceberg-rest.host = 0.0.0.0
gravitino.iceberg-rest.httpPort = ${ICEBERG_REST_PORT}
gravitino.iceberg-rest.catalog-backend = jdbc
gravitino.iceberg-rest.warehouse = ${ICEBERG_WAREHOUSE}
gravitino.iceberg-rest.jdbc-initialize = true
gravitino.iceberg-rest.jdbc-driver = org.h2.Driver
gravitino.iceberg-rest.uri = ${ICEBERG_JDBC_URI}
gravitino.iceberg-rest.io-impl = org.apache.iceberg.aws.s3.S3FileIO
gravitino.iceberg-rest.s3-endpoint = ${ICEBERG_MINIO_ENDPOINT}
gravitino.iceberg-rest.s3-path-style-access = true
gravitino.iceberg-rest.s3-access-key-id = ${MINIO_ROOT_USER}
gravitino.iceberg-rest.s3-secret-access-key = ${MINIO_ROOT_PASSWORD}
gravitino.iceberg-rest.s3-region = ${ICEBERG_AWS_REGION}
